# Generated by Django 4.1.3 on 2022-12-04 20:59

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='image',
            field=models.ImageField(default='https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png', upload_to=teacher.services.models_services.generate_file_name),
            preserve_default=False,
        ),
    ]
