# Generated by Django 4.1.3 on 2022-12-08 14:01

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_classroom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(upload_to=teacher.models.subject_file_name),
        ),
    ]
