# Generated by Django 4.1.3 on 2022-12-12 11:41

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentwork_is_checked'),
        ('teacher', '0011_alter_subject_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homework',
            new_name='HomeTask',
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(default='placeholder-image.png', upload_to=teacher.models.subject_file_name),
        ),
    ]
