# Generated by Django 4.1.3 on 2022-12-12 12:02

from django.db import migrations, models
import django.db.models.deletion
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_rename_homework_hometask_alter_subject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesHT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=teacher.models.ht_file_name)),
                ('home_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.hometask')),
            ],
        ),
    ]
