# Generated by Django 4.1.3 on 2023-04-22 19:06

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_alter_subject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='key',
            field=models.CharField(default=teacher.models.get_random_string, max_length=50, unique=True),
        ),
    ]
