# Generated by Django 4.1.3 on 2022-11-29 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_homework'),
        ('accounts', '0005_remove_student_teacher_student_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='teacher.classroom'),
        ),
    ]
