# Generated by Django 4.1.3 on 2022-12-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0004_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='homework_images')),
                ('home_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.homework')),
            ],
        ),
    ]
