# Generated by Django 4.1.3 on 2022-12-02 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_student_classroom'),
        ('student', '0002_studentwork_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwork',
            name='student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
            preserve_default=False,
        ),
    ]
