# Generated by Django 4.1.3 on 2022-12-14 01:08

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentwork_is_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesSW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=student.models.sw_file_name)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentwork')),
            ],
        ),
    ]
