# Generated by Django 4.1.3 on 2022-12-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_imagessw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentwork',
            name='image',
        ),
    ]
